[package]
name = "kodanu_math"
version = "1.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

description = "Mathematics primitives and operations for the Kodanu game engine"
keywords = ["game-engine", "gamedev", "math", "graphics"]
categories = ["game-development", "mathematics"]

[lib]
path = "src/_lib.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--document-private-items"]

[dependencies]
serde = { workspace = true }

kodanu_ecs = { workspace = true }
