[package]
name = "kodanu"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/_lib.rs"

[dependencies]
kodanu_app = { workspace = true }
kodanu_camera = { workspace = true }
kodanu_ecs = { workspace = true }
kodanu_graphics = { workspace = true }
kodanu_input = { workspace = true }
kodanu_math = { workspace = true }
kodanu_transform = { workspace = true }
kodanu_window = { workspace = true }
kodanu_time = { workspace = true }
kodanu_plugins = { workspace = true }

kodanu_physics = { workspace = true, optional = true }
kodanu_macros = { workspace = true, optional = true }

[features]
default = ["physics", "macros"]

physics = ["dep:kodanu_physics"]
macros = ["dep:kodanu_macros"]
