[package]
name = "kodanu_app"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/_lib.rs"

[dependencies]
pollster = { workspace = true }

kodanu_window = { workspace = true }
kodanu_ecs = { workspace = true }
kodanu_time = { workspace = true }
kodanu_math = { workspace = true }
kodanu_graphics = { workspace = true }
