[package]
name = "kodanu_time"
version = "1.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

description = "Time management and frame timing for the Kodanu engine."
keywords = ["game-engine", "gamedev", "time"]
categories = ["game-development"]

[lib]
path = "src/_lib.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--document-private-items"]

[dependencies]
serde = { workspace = true }

kodanu_ecs = { workspace = true }
